package me.redbaby.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.redbaby.greendao.Table_shopping;

import me.redbaby.greendao.Table_shoppingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig table_shoppingDaoConfig;

    private final Table_shoppingDao table_shoppingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        table_shoppingDaoConfig = daoConfigMap.get(Table_shoppingDao.class).clone();
        table_shoppingDaoConfig.initIdentityScope(type);

        table_shoppingDao = new Table_shoppingDao(table_shoppingDaoConfig, this);

        registerDao(Table_shopping.class, table_shoppingDao);
    }
    
    public void clear() {
        table_shoppingDaoConfig.getIdentityScope().clear();
    }

    public Table_shoppingDao getTable_shoppingDao() {
        return table_shoppingDao;
    }

}
