package me.redbaby.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.redbaby.greendao.Table_shopping;
import me.redbaby.greendao.Table_order;

import me.redbaby.greendao.Table_shoppingDao;
import me.redbaby.greendao.Table_orderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig table_shoppingDaoConfig;
    private final DaoConfig table_orderDaoConfig;

    private final Table_shoppingDao table_shoppingDao;
    private final Table_orderDao table_orderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        table_shoppingDaoConfig = daoConfigMap.get(Table_shoppingDao.class).clone();
        table_shoppingDaoConfig.initIdentityScope(type);

        table_orderDaoConfig = daoConfigMap.get(Table_orderDao.class).clone();
        table_orderDaoConfig.initIdentityScope(type);

        table_shoppingDao = new Table_shoppingDao(table_shoppingDaoConfig, this);
        table_orderDao = new Table_orderDao(table_orderDaoConfig, this);

        registerDao(Table_shopping.class, table_shoppingDao);
        registerDao(Table_order.class, table_orderDao);
    }
    
    public void clear() {
        table_shoppingDaoConfig.getIdentityScope().clear();
        table_orderDaoConfig.getIdentityScope().clear();
    }

    public Table_shoppingDao getTable_shoppingDao() {
        return table_shoppingDao;
    }

    public Table_orderDao getTable_orderDao() {
        return table_orderDao;
    }

}
